name: Main

on:
  push:
    branches: [main]

jobs:
  unit-tests:
    name: Unit tests
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      exclude_swift_versions: "[{\"swift_version\": \"5.8\"}, {\"swift_version\": \"5.9\"}, {\"swift_version\": \"5.10\"}]"
      swift_flags: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      swift_nightly_flags: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
