name: Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "Swift WebAuthn"
      shell_check_enabled: false
      format_check_enabled: false
      license_header_check_enabled: false
      docs_check_enabled: false
      yamllint_check_enabled: false

  unit-tests:
    name: Unit tests
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      swift_flags: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      swift_nightly_flags: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
